# Generated by Django 5.1.4 on 2025-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Fjob',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Mjob',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Pstatus',
            field=models.CharField(choices=[('T', 'Living together'), ('A', 'Separated')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='activities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='famsize',
            field=models.CharField(choices=[('LE3', 'Less than or equal to 3'), ('GT3', 'Greater than 3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='famsup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='higher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='nursery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='romantic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolsup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
