# Generated by Django 5.1.4 on 2025-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_fjob_student_mjob_student_pstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Pstatus',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='famsize',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
